version: "3.8"

services:
    flyway:
        image: flyway/flyway
        command: -url=jdbc:${PROD_DB_URL} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -locations=filesystem:/flyway/sql migrate
        volumes:
            - ./api/sql:/flyway/sql

    backend:
        build:
            context: ./api
            dockerfile: Dockerfile.prod
        environment:
            SIGNING_KEY: ${SIGNING_KEY}
            ALGORITHM: ${ALGORITHM}
            VITE_API_HOST: ${VITE_API_HOST}
            CORS_HOST: ${CORS_HOST}
            DATABASE_URL: ${PROD_DB_URL}
        ports:
            - "443:443"

    frontend:
        build:
            context: ./drive-stats
            dockerfile: Dockerfile.prod
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./drive-stats/assets:/usr/share/nginx/html/assets
        depends_on:
            - backend
