version: "3.8"

volumes:
    drive-statsDB:
        external: true

services:
    fastapi:
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - "8000:8000"
        environment:
            CORS_HOST: http://localhost:5173
            DATABASE_URL: postgresql://casper:foTVdhgYZzz8bOL6e@postgres:5432/drivestats_db
            SIGNING_KEY: 2e2f446477efb5db3c21276786a5d7a431b671ab440fdf8d7e84368cc198b562
            VITE_API_HOST: localhost:8000
        volumes:
            - ./api:/app
        depends_on:
            postgres:
                condition: service_healthy
        command: >
            bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
        user: "1000:1000"

    drive-stats:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        environment:
            VITE_API_HOST: http://localhost:8000
        ports:
            - "5173:5173"
        user: "1000:1000"
        volumes:
            - ./drive-stats:/app

    postgres:
        image: postgres:16.2
        ports:
            - "5432:5432"
        volumes:
            - drive-statsDB:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: drivestats_db
            POSTGRES_USER: casper
            POSTGRES_PASSWORD: foTVdhgYZzz8bOL6e
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U casper -d drivestats_db"]
            interval: 10s
            timeout: 5s
            retries: 5

    flyway:
        image: flyway/flyway:latest
        command: -configFiles=/flyway/flyway.conf migrate
        volumes:
            - ./api/sql:/flyway/sql
            - ./api/flyway.conf:/flyway/flyway.conf
        depends_on:
            - postgres
