version: "3.8"

volumes:
    drive-statsDB:
        external: true

services:
    fastapi:
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - "8000:8000"
        environment:
            CORS_HOST: ${CORS_HOST}
            DATABASE_URL: ${DATABASE_URL}
            SIGNING_KEY: ${SIGNING_KEY}
            VITE_API_HOST: ${VITE_API_HOST}
        volumes:
            - ./api:/app
        depends_on:
            postgres:
                condition: service_healthy
        command: >
            bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
        user: "1000:1000"

    drive-stats:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        environment:
            VITE_API_HOST: ${VITE_API_HOST}
        ports:
            - "5173:5173"
        user: "1000:1000"
        volumes:
            - ./drive-stats:/app

    postgres:
        image: postgres:16.2
        ports:
            - "5432:5432"
        volumes:
            - drive-statsDB:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    flyway:
        image: flyway/flyway:latest
        command: -configFiles=/flyway/flyway.conf migrate
        volumes:
            - ./api/sql:/flyway/sql
            - ./api/flyway.conf:/flyway/flyway.conf
        depends_on:
            - postgres
