version: "3.8"

services:
    postgres:
        image: postgres:16.2
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-drivestats_db}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        volumes:
            - drive-statsDB:/var/lib/postgresql/data
        networks:
            - app-network

    flyway:
        image: flyway/flyway
        command: migrate
        volumes:
            - ./sql:/flyway/sql
        environment:
            FLYWAY_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-drivestats_db}
            FLYWAY_USER: ${POSTGRES_USER:-postgres}
            FLYWAY_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            FLYWAY_LOCATIONS: filesystem:/flyway/sql
        depends_on:
            - postgres
        networks:
            - app-network

    backend:
        build:
            context: ./api
            dockerfile: Dockerfile.dev
        environment:
            SIGNING_KEY: ${SIGNING_KEY}
            ALGORITHM: ${ALGORITHM:-HS256}
            VITE_API_HOST: ${VITE_API_HOST:-https://localhost:8000}
            CORS_HOST: ${CORS_HOST:-https://localhost}
            DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-drivestats_db}
        ports:
            - "8000:8000"
        depends_on:
            - postgres
            - flyway
        networks:
            - app-network

    frontend:
        build:
            context: ./drive-stats
            dockerfile: Dockerfile.dev
        ports:
            - "5173:5173" # Vite default dev port
        volumes:
            - ./drive-stats:/app # Mount the frontend source code
        environment:
            CHOKIDAR_USEPOLLING: "true" # Enable polling for file changes if necessary
        networks:
            - app-network

volumes:
    drive-statsDB:

networks:
    app-network:
