# Use an official node image as a base
FROM node:lts-bullseye AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Use a minimal nginx image as a base
FROM nginx:alpine

# Copy the built application from the previous stage
COPY --from=build /app/dist /usr/share/nginx/html

# Copy custom nginx configuration
COPY dev_nginx.conf /etc/nginx/nginx.conf

# Copy assets directory
COPY assets /usr/share/nginx/html/assets

# Copy SSL certificates
COPY self-signed-cert/selfsigned.crt /etc/nginx/conf.d/selfsigned.crt
COPY self-signed-cert/selfsigned.key /etc/nginx/conf.d/selfsigned.key

# Expose port 80 and 443
EXPOSE 80 443

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
