FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip

WORKDIR /app

COPY api/requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt

COPY api /app
COPY tests /app/tests

CMD ["pytest", "--maxfail=1", "--disable-warnings"]
